version: 2
updates:
  # Enable version updates for Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "maintainers"
    assignees:
      - "maintainers"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    ignore:
      # Ignore patch releases for stable dependencies
      - dependency-name: "urllib3"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "requests"
        update-types: ["version-update:semver-patch"]
    groups:
      # Group development dependencies
      dev-dependencies:
        patterns:
          - "pytest*"
          - "black"
          - "ruff"
          - "mypy"
          - "bandit"
          - "pre-commit"
      # Group testing dependencies
      testing:
        patterns:
          - "*test*"
          - "*mock*"
          - "faker"
          - "hypothesis"
      # Group linting and formatting
      code-quality:
        patterns:
          - "black"
          - "ruff"
          - "mypy"
          - "isort"
          - "flake8*"
          - "pylint"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "maintainers"
    assignees:
      - "maintainers"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      # Group GitHub Actions updates
      actions:
        patterns:
          - "*"

  # Enable version updates for Docker (if we add Dockerfile later)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "maintainers"
    assignees:
      - "maintainers"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
